# Generated by Django 5.2.7 on 2025-10-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_number', models.CharField(max_length=20, unique=True, verbose_name='WA number')),
                ('client_number', models.CharField(max_length=50, verbose_name='Client project number')),
                ('drm_ref_number', models.CharField(max_length=20, verbose_name='DrM project reference number')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('client_title', models.CharField(max_length=100, verbose_name='Client title')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('vds_status', models.CharField(max_length=15, verbose_name='VDS status')),
                ('stub', models.CharField(max_length=100, verbose_name='Stub')),
                ('discipline', models.CharField(max_length=100, verbose_name='Discipline')),
                ('document_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Document number')),
                ('client_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client number')),
                ('supplier_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier number')),
                ('revision_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Revision number')),
                ('required_by', models.DateField(blank=True, null=True, verbose_name='Required by')),
                ('first_issue', models.DateField(blank=True, null=True, verbose_name='First issue')),
                ('latest_issue', models.DateField(blank=True, null=True, verbose_name='Latest issue')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='Next due')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notes')),
                ('penalty', models.BooleanField(default=False, verbose_name='Penalty')),
                ('milestone', models.BooleanField(default=False, verbose_name='Milestone')),
                ('priority', models.BooleanField(default=False, verbose_name='Priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vds.project')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=10, verbose_name='Revision number')),
                ('date', models.DateField(verbose_name='Date')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('prepared_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prepared by')),
                ('reviewed_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='Reviewed by')),
                ('approved_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='Approved by')),
                ('notes', models.CharField(blank=True, default='', max_length=50, verbose_name='Notes')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='vds.document')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(verbose_name='Date sent')),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('notes', models.CharField(blank=True, default='', max_length=100, verbose_name='Notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittals', to='vds.project')),
            ],
            options={
                'verbose_name': 'Transmittal',
                'verbose_name_plural': 'Transmittals',
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('client_number', None), _negated=True), fields=('client_number',), name='unique_client_number_not_null'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_number', None), _negated=True), fields=('supplier_number',), name='unique_supplier_number_not_null'),
        ),
    ]
