# Generated by Django 5.2.7 on 2025-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stub',
            field=models.CharField(default='NLi', max_length=10, verbose_name='Project Stub'),
            preserve_default=False,
        ),
    ]
