# Generated by Django 5.2.7 on 2025-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0002_project_stub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='vds_status',
            field=models.CharField(default='Active', max_length=15, verbose_name='VDS status'),
        ),
    ]
