# Generated by Django 5.2.7 on 2025-10-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0003_alter_document_vds_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='transmittal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='vds.transmittal'),
            preserve_default=False,
        ),
    ]
