# Generated by Django 5.2.7 on 2025-10-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0004_revision_transmittal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('document', 'revision_number'), name='unique_revision_per_document'),
        ),
    ]
