# Generated by Django 5.2.7 on 2025-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0005_revision_unique_revision_per_document'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('transmittal', 'document'), name='unique_document_per_transmittal'),
        ),
    ]
