# Generated by Django 5.2.7 on 2025-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0006_revision_unique_document_per_transmittal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmittal',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Number'),
        ),
    ]
